name: lint_python
on: [pull_request, push]
jobs:
  lint_python:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.7]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - run: pip install bandit black codespell flake8 isort mypy pytest pyupgrade safety wheel
      - run: bandit --recursive --skip B101 . || true
      - run: black --check . || true
      - run: codespell --ignore-words-list="humber,ons" --quiet-level=2 || true
      - run: flake8 . --count --max-line-length=133 --show-source --statistics
      - run: isort --check-only --profile black . || true
      - run: pip install -r requirements.txt
      - run: mypy --ignore-missing-imports .
      - run: pytest . || true
      - run: pytest --doctest-modules . || true
      - run: shopt -s globstar && pyupgrade --py37-plus **/*.py || true
      - run: safety check
